DOCKER_IMAGE_NAME=noop
DOCKER_IMAGE_VERSION=0.6

# Define the root of the local git clone for the common rules to be able 
# know where they are running from.
REPOROOT=../../..
# Include the common rules.
# Use "make targets" to see them. 
include ../../makefile.common

