from data_processing_ray.test_support.transform.noop_transform import NOOPRayTransformConfiguration
from data_processing_ray.test_support.transform.noop_folder_transform import NOOPFolderRayTransformConfiguration
