name: Feature request
title: "[Feature] "
description: Request a new capability
labels: ["enhancement"]
body:
    - type: markdown
      attributes:
          value: |
              Thank you for suggesting a new feature!

    - type: checkboxes
      attributes:
          label: Search before asking
          description: >
              Please make sure to search in the [issues](https://github.com/IBM/data-prep-lab/issues) first to see
              whether the same request was reported already.
          options:
              - label: >
                    I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.
                required: true

    - type: dropdown
      attributes:
          label: Component
          description: |
              What component would implement this new feature.
          multiple: true
          options:
              - KFP workflows
              - Library/core
              - Library/kfp
              - Tools/ingest2parquet
              - Transforms/code/code_quality
              - Transforms/code/proglang_select
              - Transforms/code/malware
              - Transforms/universal/doc_id
              - Transforms/universal/ededup
              - Transforms/universal/fdedup
              - Transforms/universal/noop
              - Transforms/universal/tokenization
              - Transforms/Other
              - Other
      validations:
          required: true

    - type: textarea
      attributes:
          label: Feature
          description: Describe the new functionality
          placeholder: >
              Please describe the new capability including its core addition and any special cases that 
              need to be addressed.

              **NOTE**: please copy and paste texts instead of taking screenshots of them for easy future search.
      validations:
          required: true

    - type: checkboxes
      attributes:
          label: Are you willing to submit a PR?
          description: >
              This is absolutely not required, but we are happy to guide you in the contribution process
              especially if you already have a good understanding of how to implement the fix.
          options:
              - label: Yes I am willing to submit a PR!

    - type: markdown
      attributes:
          value: "Thanks for completing our form!"
