
# Define the root of the local git clone for the common rules to be able 
# know where they are running from.
REPOROOT=../../..
# Include the common rules.
# Use "make help" to see them. 
include ../../makefile.transforms

DOCKER_IMAGE_NAME=blocklisting
DOCKER_IMAGE_VERSION=0.1.0

# Use default rule inherited from makefile.common
clean: .clean

# Use default rule inherited from makefile.common
test: .test

# Use default rule inherited from makefile.common
image: .image

# Use default rule inherited from makefile.common
build: .build

# Use default rule inherited from makefile.common
venv: .venv

# Use default rule inherited from makefile.common
install_lib_source: .install_lib_source


