spark.app.name: cma-spark-driver-test-local
spark.driver.memory: 1g
spark.executor.instances: 2
spark.executor.memory: 1g
spark.executor.cores: 1
spark.sql.shuffle.partitions: 2
spark.task.cpus: 1
spark.sql.legacy.parquet.nanosAsLong: true
