# Define the root of the local git clone for the common rules to be able
# know where they are running from.
REPOROOT=../../..

# TODO: handle reconcile-requirement in super pipeline
.reconcile-requirement::
