# Define the root of the local git clone for the common rules to be able 
# know where they are running from.
REPOROOT=../../..
# Include a library of common .transform.* targets which most
# transforms should be able to reuse.  However, feel free
# to override/redefine the rules below. 
include ../../.make.transforms

TRANSFORM_NAME=fdedup
# $(REPOROOT)/.make.versions file contains the versions
DOCKER_IMAGE_VERSION=${FDEDUP_VERSION}

venv::	.transforms.venv

build::	.transforms.build

test::	.transforms.test

clean:: .transforms.clean

image:: .transforms.image

test-src:: .transforms.test-src

setup:: .transforms.setup

test-image:: .transforms.test-image-help
	@echo WARNING: Skipping pytest test until we have a test/test_fdedup.py file.

publish:: .transforms.publish
