name: Test Data Connector lib

on:
    workflow_dispatch:
    push:
        branches:
            - "dev"
            - "releases/**"
        tags:
            - "*"
        paths:
            - "data-connector-lib/**"
            - "!data-connector-lib/**.md"
            - ".make.*"
    pull_request:
        branches:
            - "dev"
            - "releases/**"
        paths:
            - "data-connector-lib/**"
            - "!data-connector-lib/**.md"
            - ".make.*"

jobs:
    test-dpk-connector:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test dpk_connector
              run: |
                  make -C data-connector-lib venv test
