#
# This file was built manually as it does not follow the same structure as other transforms function
#
name: Test - transforms/chain
on:
    workflow_dispatch:
    push:
        branches:
            - "dev"
            - "releases/**"
            - "feature/**"
        tags:
            - "*"
        paths:
            - ".make.*"
            - "transforms/.make.transforms"
            - "transforms/chain/**"
            - "data-processing-lib/**"
            - "!**.md"
            - "!**/doc/**"
            - "!**/images/**"
            - "!**.gitignore"
    pull_request:
        branches:
            - "dev"
            - "releases/**"
            - "feature/**"
        paths:
            - ".make.*"
            - "transforms/.make.transforms"
            - "transforms/chain/**"
            - "data-processing-lib/**"
            - "!**.md"
            - "!**/doc/**"
            - "!**/images/**"
            - "!**.gitignore"
# Taken from https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
    test-src:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test transform source in transforms/chain
              run: |
                  if [ -e "transforms/chain/Makefile" ]; then
                      make -C transforms/chain test-src
                  else
                      echo "transforms/chain/Makefile not found - source testing Not available for this package."
                  fi