name: Test DPK Connector

on:
    workflow_dispatch:
    push:
        branches:
            - "dev"
            - "releases/**"
        tags:
            - "*"
        paths:
            - "dpk_connector/**"
            - "!dpk_connector/**.md"
    pull_request:
        branches:
            - "dev"
            - "releases/**"
        paths:
            - "dpk_connector/**"
            - "!dpk_connector/**.md"

jobs:
    test-dpk-connector:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test dpk_connector
              run: |
                  make -C dpk_connector venv test
