name: Test - miscellaneous

on:
    workflow_dispatch:
    push:
        branches:
            - "dev"
            - "releases/**"
        tags:
            - "*"
        paths-ignore:
            - ".make.*"
            - "**.md"
            - "examples/**"
            - "**/doc/**"
            - "**/images/**"
            - "**/.gitignore"
            - "**/.dockerignore"
    pull_request:
        branches:
            - "dev"
            - "releases/**"
        paths-ignore:
            - ".make.*"
            - "**.md"
            - "examples/**"
            - "**/doc/**"
            - "**/images/**"
            - "**/.gitignore"
            - "**/.dockerignore"

jobs:
    test-make:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test top-level recursive make targets.
              run: |
                  make -n clean test build publish set-versions
    check-transform-test-workflows:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Make sure all transforms have a test workflow
              run: bash scripts/check-workflows.sh
    check-licensing:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Make repo content includes license headers.
              run: bash scripts/check-licensing.sh
